
import './globals.scss';
import {Footer, MainWrapper} from '@/components';
import Header from '@/components/Header/Header';
// import { StoreProvider } from '@/redux/StoreProvider';


export const metadata = {
  title: 'Awe Buket',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="ru">
      <body>
        <Header/>
        {/*<StoreProvider>*/}
        <MainWrapper>
          {children}
        </MainWrapper>
        {/*</StoreProvider>*/}
        <Footer/>
      </body>
    </html>
  );
}
