import './globals.scss';
import {Footer, Header, MainWrapper} from '@/components';


export const metadata = {
  title: 'Awe Buket',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="ru">
      <body>
        <Header/>
        <MainWrapper>
          {children}
        </MainWrapper>
        <Footer/>
      </body>

    </html>
  );
}
